name: Deploy to EC2

on:
  workflow_dispatch:   # allows you to trigger it manually in GitHub UI
  push:                # also runs on every push
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          echo "Deploying to EC2..."
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_HOST }} <<'EOF'
            set -e
            echo "Stopping service..."
            sudo systemctl stop dev.ummumeen-api || true

            echo "Cleaning deploy directory..."
            rm -rf /home/ubuntu/system-storage/apps/dev.ummumeen-api/*

            echo "Extracting new release..."
            # here you’d usually upload and extract a tarball
            # but for testing you could also just restart or echo something

            echo "Starting service..."
            sudo systemctl start dev.ummumeen-api

            echo "Deployment done!"
          EOF
