name: Deploy to EC2

on:
  workflow_dispatch:     # Manual trigger in GitHub UI
  push:                 # Trigger on any push
    branches:
      - '**'            # On all branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          echo "Deploying to EC2..."
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_HOST }} <<'EOF'
            set -e

            echo "Stopping service..."
            sudo systemctl stop dev.ummumeen-api || true

            echo "Cleaning deploy directory..."
            rm -rf /home/ubuntu/system-storage/apps/dev.ummumeen-api/*

            echo "Extracting new release..."
            # Add your tarball extraction or deployment commands here if needed

            echo "Starting service..."
            sudo systemctl start dev.ummumeen-api

            echo "Deployment done!"
          EOF
