name: Deploy NestJS app to EC2

on:
  workflow_dispatch:   # manual trigger in GitHub UI
  push:
    branches:
      - develop       # run on pushes to develop branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Package build folder
        run: |
          tar -czf app.tar.gz ./dist

      - name: Upload tarball to EC2
        run: |
          scp -o StrictHostKeyChecking=no app.tar.gz ubuntu@${{ secrets.SERVER_HOST }}:/home/ubuntu/

      - name: SSH and deploy on EC2
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_HOST }} <<'EOF'
            set -e

            echo "Stopping systemd service dev.ummumeen-api..."
            sudo systemctl stop dev.ummumeen-api || true

            echo "Cleaning old app files..."
            rm -rf /home/ubuntu/system-storage/apps/dev.ummumeen-api/*

            echo "Extracting new build..."
            tar -xzf /home/ubuntu/app.tar.gz -C /home/ubuntu/system-storage/apps/dev.ummumeen-api/

            echo "Starting systemd service dev.ummumeen-api..."
            sudo systemctl start dev.ummumeen-api

            echo "Deployment complete!"
          EOF
